# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buying_intent.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62uying_intent.proto\x12\rbuying_intent\"e\n\x0eUserBuyingInfo\x12\x10\n\x08userName\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x1d\n\x15lastActivityTimestamp\x18\x04 \x01(\x03\"1\n\x14\x42uyingIntentResponse\x12\x19\n\x11\x62uyingIntentScore\x18\x01 \x01(\x05\x32l\n\x13\x42uyingIntentService\x12U\n\x0fGetBuyingIntent\x12\x1d.buying_intent.UserBuyingInfo\x1a#.buying_intent.BuyingIntentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buying_intent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERBUYINGINFO']._serialized_start=38
  _globals['_USERBUYINGINFO']._serialized_end=139
  _globals['_BUYINGINTENTRESPONSE']._serialized_start=141
  _globals['_BUYINGINTENTRESPONSE']._serialized_end=190
  _globals['_BUYINGINTENTSERVICE']._serialized_start=192
  _globals['_BUYINGINTENTSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
