# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from . import buying_intent_pb2 as buying__intent__pb2


class BuyingIntentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBuyingIntent = channel.unary_unary(
                '/buying_intent.BuyingIntentService/GetBuyingIntent',
                request_serializer=buying__intent__pb2.UserBuyingInfo.SerializeToString,
                response_deserializer=buying__intent__pb2.BuyingIntentResponse.FromString,
                )


class BuyingIntentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBuyingIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyingIntentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBuyingIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyingIntent,
                    request_deserializer=buying__intent__pb2.UserBuyingInfo.FromString,
                    response_serializer=buying__intent__pb2.BuyingIntentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buying_intent.BuyingIntentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyingIntentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBuyingIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/buying_intent.BuyingIntentService/GetBuyingIntent',
            buying__intent__pb2.UserBuyingInfo.SerializeToString,
            buying__intent__pb2.BuyingIntentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
